
import { Sentence, Chapter } from './types';

export const ALL_SENTENCES: Sentence[] = [
  // --- 1-100 ---
  { id: 1, korean: "그말 취소 할께. / 방금 한 말 취소", english: "I take that back." },
  { id: 2, korean: "내 폰이 없어졌어.", english: "My phone is missing." },
  { id: 3, korean: "나 완전 멘붕이야.", english: "I'm falling apart." },
  { id: 4, korean: "커피는 내가 쏠게.", english: "Coffee's on me." },
  { id: 5, korean: "나 커피 마시며 쉬는 중이야.", english: "I'm on a coffee break." },
  { id: 6, korean: "피부가 뒤집어졌어.", english: "My skin is breaking out." },
  { id: 7, korean: "독감이 유행이래.", english: "The Flu is going around." },
  { id: 8, korean: "따뜻하게 입고 다녀. 꽁꽁 싸매고 다녀.", english: "Bundle up." },
  { id: 9, korean: "네 생각은 뭔데?", english: "What's on your mind?" },
  { id: 10, korean: "조만간 한번 보자.", english: "Let's catch up soon." },
  { id: 11, korean: "우유가 다 떨어졌어.", english: "I'm out of milk." },
  { id: 12, korean: "(음식을) 뒤집어.", english: "Turn it over." },
  { id: 13, korean: "저는 자녀가 두 명 있어요.", english: "I have two kids." },
  { id: 14, korean: "저는 결혼했어요.", english: "I'm married." },
  { id: 15, korean: "저는 싱글이에요.", english: "I'm single." },
  { id: 16, korean: "현금으로 하시겠어요? 카드로 하시겠어요?", english: "Cash or card?" },
  { id: 17, korean: "많이 보고 싶었어.", english: "I missed you a lot." },
  { id: 18, korean: "(쇼핑중에) 새거 있나요?", english: "Can I get a new one?" },
  { id: 19, korean: "날 그냥 혼자 내버려 둬.", english: "Just leave me alone." },
  { id: 20, korean: "너 내일 바쁘니?", english: "Are you busy tomorrow?" },
  { id: 21, korean: "아니, 하루 종일 한가해.", english: "No, I'm free all day." },
  { id: 22, korean: "그럼 우리 같이 놀자.", english: "Let's hang out then." },
  { id: 23, korean: "너 별일 없지?", english: "What's new with you?" },
  { id: 24, korean: "별일 없어!", english: "Not much!" },
  { id: 25, korean: "무슨일 하세요?", english: "What do you do?" },
  { id: 26, korean: "저는 영업직에 있어요.", english: "I work in sales." },
  { id: 27, korean: "저는 IT쪽 일을 하고 있어요.", english: "I work in IT." },
  { id: 28, korean: "여기서 먼가요?", english: "Is it far from here?" },
  { id: 29, korean: "(맞장구치는 표현) 재밌네.", english: "That's really interesting." },
  { id: 30, korean: "난 기억을 잘 못해.", english: "I have a bad memory." },
  { id: 31, korean: "내일은 어때?", english: "How about tomorrow?" },
  { id: 32, korean: "도움이 필요하세요?", english: "Do you need any help?" },
  { id: 33, korean: "밖에 비가 내려.", english: "It's raining outside." },
  { id: 34, korean: "얘기 좀 할 수 있을까?", english: "Can we talk?" },
  { id: 35, korean: "좋은 시간 보내.", english: "Have a great time." },
  { id: 36, korean: "추가 요금이 있나요?", english: "Is there an extra charge?" },
  { id: 37, korean: "그냥 둘러 보는 중이에요.", english: "I'm just looking around." },
  { id: 38, korean: "뭐로 할래? 뭐 먹을래? (메뉴를 고르며)", english: "What would you like?" },
  { id: 39, korean: "너 옷 예쁘다 / 멋지다.", english: "I like your outfit." },
  { id: 40, korean: "차에 기름이 다 떨어졌어.", english: "My car ran out of gas." },
  { id: 41, korean: "리필 해드릴까요?", english: "Do you want a refill?" },
  { id: 42, korean: "5시가 다 돼가.", english: "It's almost five o'clock." },
  { id: 43, korean: "(그 일은) 힘들어요.", english: "It's challenging." },
  { id: 44, korean: "내가 너한테 말 안 했니?", english: "Didn't I tell you?" },
  { id: 45, korean: "나는 사진이 잘 안 받아요.", english: "I look terrible in pictures." },
  { id: 46, korean: "너 그거 다 했니?", english: "Are you done with that?" },
  { id: 47, korean: "둘이 아는 사이니?", english: "You two know each other?" },
  { id: 48, korean: "방해해서 죄송해요.", english: "I'm sorry to bother you." },
  { id: 49, korean: "어떤게 더 좋아?", english: "Which one do you prefer?" },
  { id: 50, korean: "저녁 같이 먹자.", english: "Let's have dinner together." },
  { id: 51, korean: "커피 한잔 마시자.", english: "Let's get some coffee." },
  { id: 52, korean: "무슨 일이야?", english: "What happened?" },
  { id: 53, korean: "여기서 사진 찍어도 되나요?", english: "Can I take photos here?" },
  { id: 54, korean: "(식당에서) 뭐 드릴까요?", english: "What can I get you?" },
  { id: 55, korean: "이 셔츠는 아무데나 잘 어울려.", english: "This shirt goes with everything." },
  { id: 56, korean: "이거 너무 달달하다!", english: "This is so sweet!" },
  { id: 57, korean: "난 새로운 곳에 가보고 싶어.", english: "I want to visit new places." },
  { id: 58, korean: "메뉴판 좀 주시겠어요?", english: "Can I have a menu?" },
  { id: 59, korean: "(일) 지루해.", english: "It's boring." },
  { id: 60, korean: "나 감기 걸린 것 같아.", english: "I think I have a cold." },
  { id: 61, korean: "나도 정말 그거 하고 싶어.", english: "I'd love to do that." },
  { id: 62, korean: "너 멋지다!", english: "You look great!" },
  { id: 63, korean: "뒤로 물러서 주세요.", english: "Step back, please." },
  { id: 64, korean: "TV에서 뭐 하니? / 무슨 방송 하니?", english: "What's on TV?" },
  { id: 65, korean: "언제든지 들르세요.", english: "Feel free to drop by." },
  { id: 66, korean: "우리 어떻게 해야 하지?", english: "What should we do?" },
  { id: 67, korean: "저녁에 외식 하자.", english: "Let's go out for dinner." },
  { id: 68, korean: "주문을 변경해도 되나요?", english: "Can I change my order?" },
  { id: 69, korean: "콧물이 나와요.", english: "I have a runny nose." },
  { id: 70, korean: "한번 생각해 볼게요.", english: "Let me think about it." },
  { id: 71, korean: "무엇을 하고 싶으세요?", english: "What do you like to do?" },
  { id: 72, korean: "뭐 필요한거 없니?", english: "Do you need anything?" },
  { id: 73, korean: "라떼 한잔 주세요.", english: "I'll have a latte." },
  { id: 74, korean: "들어와.", english: "Come in." },
  { id: 75, korean: "잘 난 척 좀 그만해.", english: "Stop showing off." },
  { id: 76, korean: "나는 단것을 좋아하지 않아.", english: "I don't like sweets." },
  { id: 77, korean: "여기 정말 좋다.", english: "I love this place." },
  { id: 78, korean: "나는 오늘 회의가 있어.", english: "I have a meeting today." },
  { id: 79, korean: "계산서 좀 주시겠어요?", english: "Can I have the bill?" },
  { id: 80, korean: "나중에 다시 올게요.", english: "I'll come back later." },
  { id: 81, korean: "너 오늘 멋져 보여.", english: "You look great today." },
  { id: 82, korean: "얼마나 걸릴까요?", english: "How long will it take?" },
  { id: 83, korean: "우리 구면인가요?", english: "Have we met before?" },
  { id: 84, korean: "시간이 부족해요.", english: "I don't have enough time." },
  { id: 85, korean: "주말 잘 보내!", english: "Have a good weekend!" },
  { id: 86, korean: "좋은 하루 되세요!", english: "Have a good day!" },
  { id: 87, korean: "너 올거니?", english: "Are you going to come?" },
  { id: 88, korean: "뭐가 문제에요?", english: "What's wrong with you?" },
  { id: 89, korean: "커피 좀 주시겠어요?", english: "Can I have a coffee?" },
  { id: 90, korean: "당신은 아침형 인간입니까?", english: "Are you a morning person?" },
  { id: 91, korean: "난 채식만 해요.", english: "I'm a vegetarian." },
  { id: 92, korean: "나는 휴가를 갈 거에요.", english: "I'm going on vacation." },
  { id: 93, korean: "괜찮니? 괜찮으세요?", english: "Are you alright?" },
  { id: 94, korean: "난 너무 피곤해.", english: "I'm so tired." },
  { id: 95, korean: "너 잘하고 있어.", english: "You're doing a great job." },
  { id: 96, korean: "한번 먹어 볼래?", english: "Want to try some?" },
  { id: 97, korean: "생각해 볼게.", english: "I'll think about it." },
  { id: 98, korean: "여기 있어요.", english: "Here you go." },
  { id: 99, korean: "여기 자리 있습니까?", english: "Is this seat taken?" },
  { id: 100, korean: "전혀 관심이 없어요.", english: "I'm not interested at all." },
  
  // --- 101-200 ---
  { id: 101, korean: "지금 이순간을 즐기자.", english: "Let's enjoy this moment." },
  { id: 102, korean: "한숨도 못잤어.", english: "I couldn't sleep a wink." },
  { id: 103, korean: "정말 즐거웠어요.", english: "I had a great time." },
  { id: 104, korean: "그거 확실하니?", english: "Are you sure about that?" },
  { id: 105, korean: "누가 그러던가요?", english: "Who told you that?" },
  { id: 106, korean: "여기서 드실건가요? 가져가실 건가요?", english: "For here or to go?" },
  { id: 107, korean: "그는 다시 오지 않을 거야.", english: "He's not coming back." },
  { id: 108, korean: "나 그와 헤어졌어.", english: "I broke up with him." },
  { id: 109, korean: "난 올빼미족이 아니야.", english: "I'm not a night owl." },
  { id: 110, korean: "난 셀카 찍는 걸 좋아해.", english: "I enjoy taking selfies." },
  { id: 111, korean: "포장해 갈 수 있을 까요?", english: "Can I have that to go?" },
  { id: 112, korean: "나는 휴식이 필요해.", english: "I need a break." },
  { id: 113, korean: "괜찮아요. 저는 사양할게요.", english: "No, thanks. I'll pass." },
  { id: 114, korean: "난 상관없어.", english: "I don't care." },
  { id: 115, korean: "너 지금 바쁘니?", english: "Are you busy right now?" },
  { id: 116, korean: "명심할게요.", english: "I'll keep that in mind." },
  { id: 117, korean: "너 생일이니?", english: "Is it your birthday?" },
  { id: 118, korean: "오고 있니?", english: "Are you coming?" },
  { id: 119, korean: "이걸로 할게요.", english: "I'll take this." },
  { id: 120, korean: "저도 같은 걸로 할게요.", english: "I'll have the same." },
  { id: 121, korean: "지금 체크인 할 수 있나요?", english: "Can I check in now?" },
  { id: 122, korean: "핸드폰 챙겼니?", english: "Do you have your cellphone?" },
  { id: 123, korean: "난 매일 운동을 해요.", english: "I work out every day." },
  { id: 124, korean: "5달러 입니다.", english: "That'll be $5." },
  { id: 125, korean: "언제 헤어졌어?", english: "When did you break up?" },
  { id: 126, korean: "난 늦잠 자는 걸 좋아해", english: "I love sleeping in." },
  { id: 127, korean: "멋진 사진이네요!", english: "That's a great photo!" },
  { id: 128, korean: "저는 두명의 자매가 있어요.", english: "I have two sisters." },
  { id: 129, korean: "나 정말 스트레스 받아.", english: "I'm feeling stressed." },
  { id: 130, korean: "그거 좋겠네요.", english: "That would be nice." },
  { id: 131, korean: "난 시간이 좀 더 필요해", english: "I need more time." },
  { id: 132, korean: "너는?", english: "How about you?" },
  { id: 133, korean: "온몸이 쑤시고 아파.", english: "I ache all over." },
  { id: 134, korean: "서두를 필요 없어요.", english: "Thers's no need to hurry." },
  { id: 135, korean: "오늘 밤 시간 있으세요?", english: "Are you free tonight?" },
  { id: 136, korean: "이번 주말에 시간 괜찮니?", english: "Are you free this weekend?" },
  { id: 137, korean: "잘됐다. / 정말 축하해.", english: "I'm so happy for you." },
  { id: 138, korean: "진짜 미치겠네.", english: "I'm freaking out." },
  { id: 139, korean: "허리가 너무 아파요.", english: "My back is killing me." },
  { id: 140, korean: "지금 몇 시인가요?", english: "What time is it now?" },
  { id: 141, korean: "여기 앉아도 될까요?", english: "Do you mind if I sit here?" },
  { id: 142, korean: "내가 전원 꺼 놨어.", english: "I turned it off." },
  { id: 143, korean: "방금 이사 왔어요.", english: "I just moved in." },
  { id: 144, korean: "난 봄이 좋아.", english: "I enjoy spring." },
  { id: 145, korean: "나는 맏이에요.", english: "I'm the oldest." },
  { id: 146, korean: "그건 미안하게 됐어.", english: "I'm sorry about that." },
  { id: 147, korean: "그건 중요하지 않아요 / 그건 문제가 되지 않아요.", english: "It doesn't matter." },
  { id: 148, korean: "난 정말 심심해.", english: "I'm really bored." },
  { id: 149, korean: "너무 느끼해요. (부정적인 느낌)", english: "It's too greasy." },
  { id: 150, korean: "뭐가 문제야? / 뭐가 문제지?", english: "What's the matter?" },
  { id: 151, korean: "너 거기 가봤니?", english: "Have you been there?" },
  { id: 152, korean: "몇 번 가봤어.", english: "I've been there a few." },
  { id: 153, korean: "잘 안 들려.", english: "I can't hear you." },
  { id: 154, korean: "내가 늦은 거니?", english: "Am I late?" },
  { id: 155, korean: "진짜야? / 실화야?", english: "Are you serious?" },
  { id: 156, korean: "현금으로 계산할게요.", english: "I'll pay in cash." },
  { id: 157, korean: "감기 걸렸어요.", english: "I got a cold." },
  { id: 158, korean: "선택의 여지가 없어요.", english: "I have no choice." },
  { id: 159, korean: "만나서 반가웠어요.", english: "It was nice meeting you." },
  { id: 160, korean: "나 다이어트 중이야.", english: "I'm on a diet." },
  { id: 161, korean: "핸드폰을 꺼 주세요", english: "Please turn off your phone." },
  { id: 162, korean: "나 지금 집이야.", english: "I'm at home." },
  { id: 163, korean: "산책하러 갑시다.", english: "Let's go for a walk." },
  { id: 164, korean: "나는 화장한 날이 좋아.", english: "I like sunny days." },
  { id: 165, korean: "친구 좋다는 게 뭐니?", english: "What are friends for?" },
  { id: 166, korean: " 그곳에 어떻게 가죠?", english: "How can I get there?" },
  { id: 167, korean: "내가 나중에 알려줄게.", english: "I'll let you know later." },
  { id: 168, korean: "넌 정말 좋은 친구야.", english: "You're such a good friend." },
  { id: 169, korean: "내가 너와 함께 있어. / 나는 네 편이야.", english: "I'm with you." },
  { id: 170, korean: "신분증 좀 볼 수 있을까요?", english: "Can I see your ID?" },
  { id: 171, korean: "온라인으로 예매했어요.", english: "I have booked online." },
  { id: 172, korean: "잘 잤니?", english: "Did you sleep well?" },
  { id: 173, korean: "우리 간식 좀 먹자.", english: "Let's grap a snack." },
  { id: 174, korean: "나는 운이 좋았어.", english: "I was lucky." },
  { id: 175, korean: "미안해요.", english: "Sorry about that." },
  { id: 176, korean: "저는 재택근무를 해요.", english: "I work from home." },
  { id: 177, korean: "왜 나한테 말 안 했어?", english: "Why didn't you tell me?" },
  { id: 178, korean: "여기서 나가자.", english: "Let's go out of here." },
  { id: 179, korean: "내가 어디로 가면 되지?", english: "Where should I go?" },
  { id: 180, korean: "바람 좀 쐬러 가자.", english: "Let's get some air." },
  { id: 181, korean: "혹시 알레르기 있으세요?", english: "Do you have any allergies?" },
  { id: 182, korean: "와이파이에 접속이 안돼.", english: "I can't get WI-FI." },
  { id: 183, korean: "장난하니?", english: "Are you kidding me?" },
  { id: 184, korean: "좀 쉬어.", english: "Get some rest." },
  { id: 185, korean: "핸드폰 충전을 할 수 있나요?", english: "Can I charge my phone?" },
  { id: 186, korean: "연락하고 지내자.", english: "Let's keep in touch." },
  { id: 187, korean: "그 얘기는 하지 말자", english: "Let's not talk about it." },
  { id: 188, korean: "저녁은 내가 쏠게.", english: "Dinner is on me." },
  { id: 189, korean: "스테이크를 뒤집어.", english: "Turn the steak over." },
  { id: 190, korean: "난 소설을 아주 좋아해.", english: "I'm a fan of novels." },
  { id: 191, korean: "알겠어요.", english: "I understand." },
  { id: 192, korean: "당신의 직업이 마음에 드세요?", english: "Do you like your job?" },
  { id: 193, korean: "날 탓하지 마.", english: "Don't blame me." },
  { id: 194, korean: "난 영화 보는 걸 좋아해.", english: "I love watching films." },
  { id: 195, korean: "난 유럽에 가 봤어.", english: "I've been to Europe." },
  { id: 196, korean: "이건 베스트 셀러야.", english: "It's a bestseller." },
  { id: 197, korean: "너 걔네랑 친하니?", english: "Are you close to them?" },
  { id: 198, korean: "응, 우리는 잘 지내/친해.", english: "Yes, we get along well." },
  { id: 199, korean: "난 락 음악에 빠져있어.", english: "I'm into rock music." },
  { id: 200, korean: "아이스크림은 정말 못 참겠어.", english: "Ice cream is my weakness." },

  // --- 201-300 ---
  { id: 201, korean: "다리를 다쳤어", english: "I hurt my legs." },
  { id: 202, korean: "점점 좋아지고 있어", english: "I'm getting better." },
  { id: 203, korean: "다행이다", english: "That's good to hear." },
  { id: 204, korean: "너 지금 아프구나", english: "You're sick." },
  { id: 205, korean: "머리가 너무 아파", english: "My head is killing me." },
  { id: 206, korean: "너 괜찮니?", english: "Are you OK?" },
  { id: 207, korean: "약을 좀 먹어야겠어", english: "I need to take some medicine." },
  { id: 208, korean: "재촉하지마", english: "Don't rush me." },
  { id: 209, korean: "저를 기다리지 마세요", english: "Don't wait for me." },
  { id: 210, korean: "서둘러", english: "Hurry up." },
  { id: 211, korean: "저는 지금 당장은 바빠요", english: "I'm busy right now." },
  { id: 212, korean: "답변이 늦어서 미안해요", english: "I'm sorry for the late reply." },
  { id: 213, korean: "미안해 늦었어", english: "I'm sorry I'm late." },
  { id: 214, korean: "기다려 주세요", english: "Please wait for me." },
  { id: 215, korean: "조금만 기다려", english: "Wait a moment." },
  { id: 216, korean: "우리 시간이 없어", english: "We don't have time." },
  { id: 217, korean: "너는 이번 크리스마스에 뭐할거니?", english: "What are you doing this Christmas?" },
  { id: 218, korean: "너 언제 시간되니?", english: "When are you free?" },
  { id: 219, korean: "왜 늦었니?", english: "Why are you so late?" },
  { id: 220, korean: "같이 갈래?", english: "Do you want to join me?" },
  { id: 221, korean: "영화보러 갈꺼야", english: "I'm going to the movies." },
  { id: 222, korean: "헤어 스타일을 좀 바꾸고 싶어요", english: "I want to change my hair style." },
  { id: 223, korean: "나 머리잘랐어", english: "I had my hair cut." },
  { id: 224, korean: "너 머리예쁘다", english: "I love your hairstyle." },
  { id: 225, korean: "염색해 주세요", english: "Please dye my hair." },
  { id: 226, korean: "2kg 쪘어", english: "I gained two kilograms." },
  { id: 227, korean: "살이 빠졌어요", english: "I lost weight." },
  { id: 228, korean: "그는 과체중이야", english: "He is overweight." },
  { id: 229, korean: "얼굴에 여드름이 났어요", english: "I have a pimple on my face." },
  { id: 230, korean: "다이어트 해야해", english: "I need to go on a diet." },
  { id: 231, korean: "나 요즘 살찌고 있어", english: "I'm getting weight." },
  { id: 232, korean: "물 좀 갖다주실래요?", english: "Can I have some water?" },
  { id: 233, korean: "메뉴판 좀 갖다주시겠어요?", english: "Can we get a menu?" },
  { id: 234, korean: "각자 계산해요", english: "Let's pay separately." },
  { id: 235, korean: "물론이죠. 여기있어요", english: "Sure. Here you go." },
  { id: 236, korean: "피자주문하는게 어때?", english: "Why don't you order pizza?" },
  { id: 237, korean: "노크해주세요", english: "Knock, please." },
  { id: 238, korean: "좀 지나갈까요?", english: "May I go through?" },
  { id: 239, korean: "방해해서 미안해요", english: "Sorry to interrupt." },
  { id: 240, korean: "들어가도 될까요?", english: "Can I come in?" },
  { id: 241, korean: "그럼요", english: "Not at all." },
  { id: 242, korean: "창문 좀 열어도 될까요?", english: "Do you mind if I open the window?" },
  { id: 243, korean: "무슨 걱정거리라도 있니?", english: "Do you have any concerns?" },
  { id: 244, korean: "너무 걱정하지마", english: "Don't worry too much." },
  { id: 245, korean: "걱정마세요", english: "Don't worry." },
  { id: 246, korean: "당신 탓이 아니에요", english: "It's not your fault." },
  { id: 247, korean: "무슨일입니까?", english: "What happened?" },
  { id: 248, korean: "스트레스 받지마", english: "Don't get stressed out." },
  { id: 249, korean: "포기마세요", english: "Don't give up." },
  { id: 250, korean: "유감이야", english: "I'm sorry to hear that." },
  { id: 251, korean: "그가 정말 안됐어", english: "I feel sorry for him." },
  { id: 252, korean: "그가 어제밤에 돌아가셨어", english: "He passed away last night." },
  { id: 253, korean: "한입먹어도 돼?", english: "Can I have a bite?" },
  { id: 254, korean: "매운음식 좋아해요?", english: "Do you like spicy food?" },
  { id: 255, korean: "맛이 어때?", english: "How does it taste?" },
  { id: 256, korean: "난 복숭아 알러지가 있어요", english: "I'm allergic to peaches." },
  { id: 257, korean: "맛있어 보인다", english: "It looks delicious." },
  { id: 258, korean: "정말 맛있다", english: "It's very delicious." },
  { id: 259, korean: "냄새가 좋네요", english: "Smells good." },
  { id: 260, korean: "어떤종류의 음식을 좋아하세요", english: "What kind of food do you like?" },
  { id: 261, korean: "한번 먹어봐", english: "Please try some." },
  { id: 262, korean: "굉장히 맵네", english: "It's very spicy." },
  { id: 263, korean: "맛이 어때?", english: "How does it taste?" },
  { id: 264, korean: "너무짜", english: "It's too salty." },
  { id: 265, korean: "네가 결정해", english: "It's up to you." },
  { id: 266, korean: "나도 그렇게 생각해", english: "I think so." },
  { id: 267, korean: "네말이 맞는것같아", english: "I think you're right." },
  { id: 268, korean: "다시 생각해 볼게요", english: "I'll think about it again." },
  { id: 269, korean: "됐거든", english: "Don't bother." },
  { id: 270, korean: "그것을 강요하지마세요", english: "Don't force it." },
  { id: 271, korean: "오해하지마세요", english: "Don't get me wrong." },
  { id: 272, korean: "동의해", english: "I agree with you." },
  { id: 273, korean: "뭐라고 하셨죠?", english: "I beg your pardon." },
  { id: 274, korean: "이해가 안돼요", english: "I can't catch you." },
  { id: 275, korean: "그런 뜻이 아니였어", english: "I didn't mean it." },
  { id: 276, korean: "아무거나 상관없어", english: "I don't care." },
  { id: 277, korean: "난 그렇게 생각하지 않아", english: "I don't think so." },
  { id: 278, korean: "알고 싶지않아", english: "I don't want to know." },
  { id: 279, korean: "그러고 싶어", english: "I'd love to." },
  { id: 280, korean: "나도 잘 모르겠어", english: "I'm not sure." },
  { id: 281, korean: "안됐구나", english: "It's too bad." },
  { id: 282, korean: "내 말 좀 끝까지 들어봐", english: "Just hear me out." },
  { id: 283, korean: "신경쓰지마", english: "Never mind." },
  { id: 284, korean: "좋은 생각이야", english: "Sounds good to me." },
  { id: 285, korean: "좋을대로해", english: "Suit yourself." },
  { id: 286, korean: "내가 말한것이 바로 그거야", english: "That's what I'm saying." },
  { id: 287, korean: "믿을수없어", english: "Unbelievable!" },
  { id: 288, korean: "그게 무슨 뜻이야?", english: "What do you mean?" },
  { id: 289, korean: "어떻게 생각해?", english: "What do you think?" },
  { id: 290, korean: "너 너무 한다", english: "You are too much." },
  { id: 291, korean: "그럴 필요없어요", english: "You don't have to do it." },
  { id: 292, korean: "딱걸렸네!", english: "You got me." },
  { id: 293, korean: "그럴만한 가치도 없어", english: "It's not worth it." },
  { id: 294, korean: "그럴 기분이 아니야", english: "I don't feel like it." },
  { id: 295, korean: "햄버거에 질렸어", english: "I'm fed up with hamburgers." },
  { id: 296, korean: "나도 그래", english: "Me too." },
  { id: 297, korean: "너 농담이지?", english: "You can't be serious?" },
  { id: 298, korean: "여기 앉아도 될까요?", english: "Can I sit here?" },
  { id: 299, korean: "핸드폰을 무음으로 해놨어", english: "I put my cellphone on mute." },
  { id: 300, korean: "담배끊었어요", english: "I quit smoking." },

  // --- 301-400 ---
  { id: 301, korean: "그녀는 나랑 동갑이야", english: "She is my age." },
  { id: 302, korean: "그녀는 똑똑해", english: "She is intelligent." },
  { id: 303, korean: "나 오늘 비번이야", english: "Today is my day off." },
  { id: 304, korean: "우리는 장거리 연애를 하고있어요", english: "We're in a long distance relationship." },
  { id: 305, korean: "그는 어때?", english: "What is he like?" },
  { id: 306, korean: "커피 좀 마실래요?", english: "Would you like some coffee?" },
  { id: 307, korean: "어려보이시네요", english: "You look very young." },
  { id: 308, korean: "나이보다 어려보여요", english: "You look younger than your age." },
  { id: 309, korean: "정말 친절하시군요", english: "You're very sweet." },
  { id: 310, korean: "당신은 좋으신분 같아요", english: "You seem very nice." },
  { id: 311, korean: "인기많으시겠어요", english: "You must be popular." },
  { id: 312, korean: "당신 정말 착하시네요", english: "You have a good heart." },
  { id: 313, korean: "도와줄까?", english: "Need some help?" },
  { id: 314, korean: "아니, 내가 할수있어", english: "No, I can manage." },
  { id: 315, korean: "내 핸드폰을 잃어버렸어", english: "I lost my cellphone." },
  { id: 316, korean: "길을 잃었어", english: "I'm lost." },
  { id: 317, korean: "이거 망가졌어", english: "It's broken." },
  { id: 318, korean: "정말미안해", english: "I'm so sorry." },
  { id: 319, korean: "미안해, 내실수였어", english: "I'm sorry, it was my mistake." },
  { id: 320, korean: "너무 늦었어", english: "It's too late." },
  { id: 321, korean: "괜찮아", english: "No problem." },
  { id: 322, korean: "괜찮아", english: "That's OK." },
  { id: 323, korean: "그럴수도 있지", english: "These things happen." },
  { id: 324, korean: "마음에 든다니 다행이다", english: "Glad you like it." },
  { id: 325, korean: "그녀를 주려고 선물을 샀어", english: "I bought a gift for her." },
  { id: 326, korean: "정말 마음에 들어", english: "I love it." },
  { id: 327, korean: "널위해 준비했어", english: "Here is for you." },
  { id: 328, korean: "내 생일이 다가오고 있어", english: "My birthday is coming." },
  { id: 329, korean: "뭐 갖고 싶니?", english: "What do you want?" },
  { id: 330, korean: "너 생일이 언제니?", english: "When is your birthday?" },
  { id: 331, korean: "뭐든지 말만해", english: "You name it." },
  { id: 332, korean: "그녀는 위선적이야", english: "She's two-faced." },
  { id: 333, korean: "매우친절하시네요", english: "You're very kind." },
  { id: 334, korean: "이거 입어봐도 될까요?", english: "Can I try this on?" },
  { id: 335, korean: "계산해주세요", english: "Check please." },
  { id: 336, korean: "잠시만 기다려주세요", english: "Hold on a sec." },
  { id: 337, korean: "나 어때보여?", english: "How do I look?" },
  { id: 338, korean: "다해서 얼마에요?", english: "How much is it all together?" },
  { id: 339, korean: "얼마인가요?", english: "How much is it?" },
  { id: 340, korean: "곧 가져다 드릴게요", english: "I'll be right back." },
  { id: 341, korean: "다음번엔 내가 살게", english: "I'll treat you next time." },
  { id: 342, korean: "그냥 둘러보고 있어요", english: "I'm just looking around." },
  { id: 343, korean: "추가요금이 있나요?", english: "Is there a charge?" },
  { id: 344, korean: "너한테 잘 어울린다", english: "It looks good on you." },
  { id: 345, korean: "세일 중이에요", english: "It's on sale." },
  { id: 346, korean: "저길봐", english: "Look over there." },
  { id: 347, korean: "무엇을 도와드릴까요?", english: "May I help you?" },
  { id: 348, korean: "환불해주세요", english: "Please give me a refund." },
  { id: 349, korean: "문 좀 잡아주세요", english: "Please hold the door." },
  { id: 350, korean: "사람들이 너무 많아요", english: "There are so many people." },
  { id: 351, korean: "이건 내가 낼게", english: "This one is on me." },
  { id: 352, korean: "이건 어때?", english: "What about this?" },
  { id: 353, korean: "무엇을 찾고 있어요?", english: "What are you looking for?" },
  { id: 354, korean: "이거 어디서 샀니?", english: "Where did you buy it?" },
  { id: 355, korean: "이 차는 정말 비싸다", english: "This car is very expensive." },
  { id: 356, korean: "난 여력이 안돼", english: "I can't afford this." },
  { id: 357, korean: "이건 내가 계산할게", english: "Let me pay for this." },
  { id: 358, korean: "전부얼마에요?", english: "What's the total?" },
  { id: 359, korean: "어떤 사이즈를 원하세요?", english: "What size do you want?" },
  { id: 360, korean: "230 사이즈주세요", english: "I want 230." },
  { id: 361, korean: "먼저하세요", english: "Go ahead." },
  { id: 362, korean: "제가 먼저할게요", english: "I'll go first." },
  { id: 363, korean: "엄청 쉬워요", english: "It's a breeze." },
  { id: 364, korean: " 누가 이 문제를 풀어볼래?", english: "Who wants to solve this problem?" },
  { id: 365, korean: "이 양식을 작성해 주세요", english: "Please fill this form out." },
  { id: 366, korean: "와이파이가 안되요", english: "Wi-Fi doesn't work." },
  { id: 367, korean: "리포트다썼니?", english: "Are you finished with your report?" },
  { id: 368, korean: "리포트쓰고있어", english: "I'm working on my report." },
  { id: 369, korean: "내일까지 내야하거든", english: "It's due tomorrow." },
  { id: 370, korean: "말하기는 쉽지", english: "It's easy to say." },
  { id: 371, korean: "곧 시작할거에요", english: "It's going to start soon." },
  { id: 372, korean: "아직 안됐어요", english: "It's not yet." },
  { id: 373, korean: "아직이야", english: "Not yet." },
  { id: 374, korean: "로그인했어요", english: "I logged in." },
  { id: 375, korean: "로그아웃했어요", english: "I logged out." },
  { id: 376, korean: "그가 아직 접속중이니?", english: "Is he still online?" },
  { id: 377, korean: "질문하나해도 돼요?", english: "May I ask a question?" },
  { id: 378, korean: "잘했다", english: "Good for you." },
  { id: 379, korean: "시험은 어땠니?", english: "How was your test?" },
  { id: 380, korean: "나 수학 100점 맞았어", english: "I got a perfect score in math." },
  { id: 381, korean: "완전 망했어", english: "I'm screwed up." },
  { id: 382, korean: "다 먹었니?", english: "Are you done eating?" },
  { id: 383, korean: "뭐 먹고싶어?", english: "What do you want to have?" },
  { id: 384, korean: "점심은 좀 가볍게 먹자", english: "Let's have a light lunch." },
  { id: 385, korean: "저녁이 준비됐다", english: "Dinner is ready." },
  { id: 386, korean: "두사람이 앉을 자리가 있나요?", english: "Do you have a table for two people?" },
  { id: 387, korean: "더 먹을래?", english: "Do you want some more?" },
  { id: 388, korean: "맛있게 드세요", english: "Enjoy your meal." },
  { id: 389, korean: "저녁에 외식하자", english: "Let's go out for dinner." },
  { id: 390, korean: "뭐 좀 먹으러가자", english: "Let's grab a bite." },
  { id: 391, korean: "경찰을 불러주세요", english: "Call the police." },
  { id: 392, korean: "급한일이에요", english: "It's an emergency." },
  { id: 393, korean: "무슨일이죠?", english: "What's going on?" },
  { id: 394, korean: "난 화장실에 가야겠어", english: "I need to go to the bathroom." },
  { id: 395, korean: "소변 좀 봐야겠어요", english: "I need to pee." },
  { id: 396, korean: "갑자기 딸꾹질이 나요", english: "I suddenly have hiccups." },
  { id: 397, korean: "취했어요", english: "I'm drunk." },
  { id: 398, korean: "소화가 잘 안 돼요", english: "I can't digest well." },
  { id: 399, korean: "열이나", english: "I have a fever." },
  { id: 400, korean: "나 변비에 걸렸어", english: "I have constipation." },

  // --- 401-500 ---
  { id: 401, korean: "TV좀 끌래?", english: "Can you turn off the TV?" },
  { id: 402, korean: "엄살좀피지마", english: "Don't act like a baby." },
  { id: 403, korean: "그만 좀 얘기해", english: "Don't remind me." },
  { id: 404, korean: "침뱉지마세요", english: "Don't spit." },
  { id: 405, korean: "나도 알아", english: "I know." },
  { id: 406, korean: "이것 좀 치워", english: "Put these away." },
  { id: 407, korean: "제입장이 돼보세요", english: "Put yourself in my shoes." },
  { id: 408, korean: "너 담배끊어야해", english: "You should quit smoking." },
  { id: 409, korean: "후회하게 될걸", english: "You'll be sorry." },
  { id: 410, korean: "방이 지저분하네", english: "Your room is messed up." },
  { id: 411, korean: "바보같은 소리마", english: "Don't be silly." },
  { id: 412, korean: "나 잘때 코골아", english: "I snore when I sleep." },
  { id: 413, korean: "난 간식을 많이먹어", english: "I eat between meals a lot." },
  { id: 414, korean: "운전 조심하세요.", english: "Drive safely." },
  { id: 415, korean: "안전벨트를 매세요", english: "Fasten your seat belt." },
  { id: 416, korean: "창가에 앉고싶어요", english: "I want to sit by the window." },
  { id: 417, korean: "여행가자", english: "Let's go on a trip." },
  { id: 418, korean: "내차는 소형차야", english: "My car is compact." },
  { id: 419, korean: "운동 좀 해야겠어", english: "I need to work out." },
  { id: 420, korean: "늦잠을 잤어", english: "I overslept." },
  { id: 421, korean: "집에 거의 다왔어요", english: "I'm almost home." },
  { id: 422, korean: "나도 같이 갈래", english: "I'm coming with you." },
  { id: 223, korean: "시장에 갈꺼에요", english: "I'm going to the market." },
  { id: 424, korean: "모든일이 다 잘되고 있어요?", english: "Is everything all right?" },
  { id: 425, korean: "꿈만같다", english: "It's like a dream." },
  { id: 426, korean: "그것은 나와 상관없는 일이야", english: "It's none of my business." },
  { id: 427, korean: "별거아니야", english: "It's not a big deal." },
  { id: 428, korean: "일어날 시간이야", english: "It's time to wake up." },
  { id: 429, korean: "설거지할 시간이야", english: "It's time to wash the dishes." },
  { id: 430, korean: "시간 참 빠르네요", english: "Time really flies." },
  { id: 431, korean: "어떻게 해야해?", english: "What should I do?" },
  { id: 432, korean: "언제 이사나가세요?", english: "When are you moving out?" },
  { id: 433, korean: "너 어디가?", english: "Where are you going?" },
  { id: 434, korean: "운동을 얼마나 자주하니?", english: "How often do you work out?" },
  { id: 435, korean: "같이 빨래 개자", english: "Let's fold the laundry together." },
  { id: 436, korean: "사진한장 찍어줄래?", english: "Could you take a picture for me?" },
  { id: 437, korean: "난 도시락싸갈래", english: "I'll bring my lunchbox." },
  { id: 438, korean: "언제든 전화해", english: "Call me anytime." },
  { id: 439, korean: "집에 도착하면 전화줘", english: "Call me when you get home." },
  { id: 440, korean: "전화번호 좀 알려주실래요?", english: "Can I have your phone number?" },
  { id: 441, korean: "두번이나 전화했어", english: "I called you twice." },
  { id: 442, korean: "잘못들었어", english: "I can't hear you." },
  { id: 443, korean: "통화오래못해", english: "I can't talk for long." },
  { id: 444, korean: "이만 끊을게", english: "I gotta go." },
  { id: 445, korean: "베터리를 충전해야해요", english: "I need to charge the battery." },
  { id: 446, korean: "휴대전화를 꺼놨었어", english: "I turned it off." },
  { id: 447, korean: "나중에 다시 연락할게", english: "I'll call you back later." },
  { id: 448, korean: "내핸드폰에 베터리가 없어요", english: "My cell phone is out of battery." },
  { id: 449, korean: "다시 한번 말씀해주세요", english: "Please say it again." },
  { id: 450, korean: "왜 전화안받았어?", english: "Why didn't you answer your phone?" },
  { id: 451, korean: "여기 어둡다", english: "It's dark in here." },
  { id: 452, korean: "발밑조심해", english: "Watch your step." },
  { id: 453, korean: "조심해", english: "Be careful." },
  { id: 454, korean: "나 승진했어", english: "I got promoted." },
  { id: 455, korean: "그가 직장 그만둔거 알고 있었어?", english: "Did you know he quit the job?" },
  { id: 456, korean: "일을 그만뒀어요", english: "I quit my job." },
  { id: 457, korean: "나는 돈을 많이 벌고 싶어요", english: "I want to make a lot of money." },
  { id: 458, korean: "오늘 일찍 퇴근할게요", english: "I'm leaving early today." },
  { id: 459, korean: "볼 일이 있어서요", english: "I have some errands to run." },
  { id: 460, korean: "축하해", english: "Congratulations!" },
  { id: 461, korean: "너는 요리할줄아니?", english: "Can you cook?" },
  { id: 462, korean: "나는 음악을 듣고 있어", english: "I'm listening to music." },
  { id: 463, korean: "취미가 뭐니?", english: "What is your hobby?" },
  { id: 464, korean: "난 운동하는 것을 좋아해", english: "I like playing sports." },
  { id: 465, korean: "나도 그래", english: "Same here." },
  { id: 466, korean: "원샷이야", english: "Bottoms up!" },
  { id: 467, korean: "옛날생각이 나네요", english: "It reminds me of the past." },
  { id: 468, korean: "너 내말 듣고있니?", english: "Are you listening to me?" },
  { id: 469, korean: "말할게 있어", english: "I need to talk to you." },
  { id: 470, korean: "내가 과민반응 했어", english: "I overreacted." },
  { id: 471, korean: "맥주한잔하고 싶어요", english: "I want to have a beer." },
  { id: 472, korean: "혼잣말하고 있었어", english: "I was talking to myself." },
  { id: 473, korean: "내가 데릴러갈게", english: "I will pick you up." },
  { id: 474, korean: "날 믿어", english: "Trust me." },
  { id: 475, korean: "우리는 친해요", english: "We are close." },
  { id: 476, korean: "우리는 그렇게 친하지않아요", english: "We are not that close." },
  { id: 477, korean: "뭐가 그렇게 재미있니?", english: "What is so funny?" },
  { id: 478, korean: "그리울거야", english: "I'll be missing you." },
  { id: 479, korean: "계속연락하며 지내자", english: "Let's keep in touch." },
  { id: 480, korean: "밖에 나가자", english: "Let's go out." },
  { id: 481, korean: "무슨일이야?", english: "What's up?" },
  { id: 482, korean: "화내지마", english: "Don't get upset." },
  { id: 483, korean: "그냥 장난친거야", english: "I'm just teasing you." },
  { id: 484, korean: "물론이지. 확실해.", english: "Absolutely." },
  { id: 485, korean: "정말이야?", english: "Are you sure?" },
  { id: 486, korean: "믿을수가 없어", english: "I can't believe it." },
  { id: 487, korean: "확실해", english: "I'm sure." },
  { id: 488, korean: "현실을 받아들여", english: "Let's face it." },
  { id: 489, korean: "아마도", english: "Probably" },
  { id: 490, korean: "우리춤출까?", english: "Care to dance?" },
  { id: 491, korean: "나랑 함께 할래요?", english: "Do you want to go with me?" },
  { id: 492, korean: "난 사양할게", english: "I think I'll pass." },
  { id: 493, korean: "우리파티하자", english: "Let's have a party." },
  { id: 494, korean: "건배하자!", english: "Let's toast!" },
  { id: 495, korean: "와줘서 고마워", english: "Thank you for coming." },
  { id: 496, korean: "같이 갈래?", english: "Want to come?" },
  { id: 497, korean: "꼭오셔야해요", english: "You have to come." },
  { id: 498, korean: "앉으세요", english: "Have a seat." },
  { id: 499, korean: "정말 즐거웠어요", english: "I had a great time." },
  { id: 500, korean: "너무 늦었다", english: "I stayed too long." }
];

export const CHAPTERS: Chapter[] = [
  { id: 1, title: 'LEVEL 1', range: [1, 50] },
  { id: 2, title: 'LEVEL 2', range: [1, 100] },
  { id: 3, title: 'LEVEL 3', range: [1, 150] },
  { id: 4, title: 'LEVEL 4', range: [1, 200] },
  { id: 5, title: 'LEVEL 5', range: [1, 250] },
  { id: 6, title: 'LEVEL 6', range: [1, 300] },
  { id: 7, title: 'LEVEL 7', range: [1, 350] },
  { id: 8, title: 'LEVEL 8', range: [1, 400] },
  { id: 9, title: 'LEVEL 9', range: [1, 450] },
  { id: 10, title: 'LEVEL 10', range: [1, 500] },
];

export const THEME_COLOR = '#7c3aed';
export const SECONDARY_COLOR = '#3b82f6';
export const ACCENT_COLOR = '#ec4899';
